# Generated by Django 5.0.3 on 2024-04-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grosary', '0003_grosary_create_at_grosary_update_at_grosary_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order confirmed', 'Order Confirmed'), ('order processing', 'Order Processing'), ('order shipping', 'Order Shipping'), ('order canclled', 'Order Cancelled'), ('order delivered', 'Order Delivered')], default='order confirmed', max_length=30),
        ),
    ]
